# -*- coding: utf-8 -*-
"""Week5_Scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HEad3AF6G7HJvHBK05FwMttymuGoZL1e
"""

import pandas as pd
from bs4 import BeautifulSoup
tables=pd.read_html('https://en.wikipedia.org/wiki/Climate_Change_Performance_Index')
df=tables[2]
df.columns= ['rank','country','score']
df.sort_values(by='country')
df['country'].str.replace('*','')
df.to_csv('CCPI_data.csv')